// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Components = require("./components.bs.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(Components.ToDo[/* make */0], { }), "app");

/*  Not a pure module */
