// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function make(label) {
  return /* record */[
          /* id */Date.now().toString(),
          /* label */label,
          /* status : Pending */0
        ];
}

var Task = /* module */[/* make */make];

var Action = /* module */[];

var initial_state_001 = /* tasks : :: */[
  make("Learn Reason"),
  /* [] */0
];

var initial_state = /* record */[
  /* input */undefined,
  initial_state_001
];

function reducer(state, action) {
  var new_state;
  if (typeof action === "number") {
    var match = state[/* input */0];
    new_state = match !== undefined ? /* record */[
        /* input */undefined,
        /* tasks : :: */[
          make(match),
          state[/* tasks */1]
        ]
      ] : state;
  } else if (action.tag) {
    var id = action[0];
    var new_tasks = List.map((function (task) {
            var match = id === task[/* id */0];
            if (match) {
              return /* record */[
                      /* id */task[/* id */0],
                      /* label */task[/* label */1],
                      /* status : Done */1
                    ];
            } else {
              return task;
            }
          }), state[/* tasks */1]);
    new_state = /* record */[
      /* input */state[/* input */0],
      /* tasks */new_tasks
    ];
  } else {
    var text = action[0];
    new_state = text === "" ? /* record */[
        /* input */undefined,
        /* tasks */state[/* tasks */1]
      ] : /* record */[
        /* input */text,
        /* tasks */state[/* tasks */1]
      ];
  }
  console.log(new_state);
  return new_state;
}

var State = /* module */[
  /* initial_state */initial_state,
  /* reducer */reducer
];

exports.Task = Task;
exports.Action = Action;
exports.State = State;
/* initial_state Not a pure module */
